// AUTH
export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const CHECK_AUTH_STATE = "CHECK_AUTH_STATE";

// FETCH BOOKSHELF
export const FETCH_BOOKSHELF = "FETCH_BOOKSHELF";
export const FETCH_BOOKSHELF_START = "FETCH_BOOKSHELF_START";
export const FETCH_BOOKSHELF_SUCCESS = "FETCH_BOOKSHELF_SUCCESS";
export const FETCH_BOOKSHELF_FAIL = "FETCH_BOOKSHELF_FAIL";

// ADD BOOK
export const ADD_BOOK = "ADD_BOOK";
export const ADD_BOOK_START = "ADD_BOOK_START";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL";

// DELETE BOOK
export const DELETE_BOOK = "DELETE_BOOK";
export const DELETE_BOOK_START = "DELETE_BOOK_START";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL";

// FETCH MATCHES
export const FETCH_MATCHES = "FETCH_MATCHES";
export const FETCH_MATCHES_START = "FETCH_MATCHES_START";
export const FETCH_MATCHES_SUCCESS = "FETCH_MATCHES_SUCCESS";
export const FETCH_MATCHES_FAIL = "FETCH_MATCHES_FAIL";
